name: Test Self-Hosted Runner
 
on: [push]
 
jobs:
  test-runner:
    runs-on: self-hosted

    steps:
    - name: Check out repository
      uses: actions/checkout@v2
 
    - name: Run a script
      run: echo "Hello, world! The self-hosted runner is working."
 
